-- palio_lite_qiosk.REQUEST_HEADER definition

CREATE TABLE `REQUEST_HEADER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(32) NOT NULL,
  `F_PIN` varchar(16) NOT NULL,
  `DATE` datetime NOT NULL,
  `STATUS` smallint(6) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4;


-- palio_lite_qiosk.REQUEST_DETAIL definition

CREATE TABLE `REQUEST_DETAIL` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `REQUEST_HEADER` int(11) NOT NULL,
  `KEY` varchar(32) NOT NULL,
  `VALUES` varchar(64) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=123 DEFAULT CHARSET=utf8mb4;