ALTER TABLE palio_lite_qiosk.REQUEST_HEADER  MODIFY COLUMN `ID` varchar(32), 
DROP PRIMARY KEY, 
ADD PRIMARY KEY (`ID`);
                   
ALTER TABLE palio_lite_qiosk.REQUEST_DETAIL MODIFY COLUMN REQUEST_HEADER varchar(32) NOT NULL;
