CREATE TABLE `POST_SCORE_PARAMETER` (  
  `PARAM` VARCHAR(32) NOT NULL,
  `VALUE` DOUBLE,
  PRIMARY KEY (`PARAM`) 
);

insert  into `POST_SCORE_PARAMETER`(`PARAM`,`VALUE`) values 
('COMMENT',1200),
('LIKE',600),
('TEMP',604800000);

ALTER TABLE `POST`   
	ADD COLUMN `NEW_CONTENT` TINYINT DEFAULT 0 NULL COMMENT '1=true;0=false' AFTER `REPORT`,
	ADD COLUMN `VPREF` INT DEFAULT 0 NULL AFTER `NEW_CONTENT`;


CREATE EVENT `UPDATE_POST_SCORE` ON SCHEDULE EVERY 1 HOUR STARTS (
  TIMESTAMP(CURRENT_DATE)
) COMMENT 'update post score' DO 
UPDATE 
  POST p 
SET 
  p.SCORE = p.SCORE - (
    SELECT 
      ps.VALUE 
    FROM 
      POST_SCORE_PARAMETER ps 
    WHERE 
      ps.PARAM = "TEMP"
  ), p.NEW_CONTENT = 0 
WHERE 
  p.NEW_CONTENT = 1 
  AND p.CREATED_DATE >= FLOOR(UNIX_TIMESTAMP(NOW(3))* 1000)-3600000
